replicaCount: 1
image:
  repository: vivekbangare01/${{ values.app_name }}
  pullPolicy: IfNotPresent
  tag: "${{values.app_name}}-{{values.app_env}}-latest"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ${{ values.app_name }}-${{ values.app_env }}.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}

livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: 8080
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: 8080
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
