name: ${{ values.app_name }}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}

    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vivekbangare01/${{ values.app_name }}:${{ '${{ env.COMMIT_ID }}' }}

  cd:
    needs: ci
    runs-on: self-hosted

    concurrency:
      group: update-values-main
      cancel-in-progress: false

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with main
        shell: bash
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Modify values file
        shell: bash
        run: |
          echo "${{ '${{ needs.ci.outputs.commit_id }}' }}"

          curl -L \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o /tmp/yq

          chmod +x /tmp/yq

          /tmp/yq -i \
            '.image.tag = "${{ '${{ needs.ci.outputs.commit_id }}' }}"' \
            charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

          echo "Updated image tag:"
          /tmp/yq '.image.tag' \
            charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml
          message: "Updates values.yaml with commit ${{ '${{ needs.ci.outputs.commit_id }}' }}"

      - name: Install Argo CD
        shell: bash
        run: |
          curl -ksSL \
            -o argocd \
            https://argocd-server.argocd/download/argocd-linux-amd64

          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argo CD app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password "${{ '${{ secrets.ARGOCD_PASSWORD }}' }}"

          argocd app sync ${{ values.app_name }}